{{ if .Values.solvers.installDefaults }}

apiVersion: kubesolv.io/v1
kind: Solver
metadata:
    name: nissy-light
spec:
    description: Nissy Light Solver. See https://nissy.tronto.net/.
    image: {{ .Values.imagePrefix }}kubesolv/nissy-light:2.0.8
    mode: standalone

{{ end }}
