apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cubestates.kubesolv.io
spec:
  scope: Namespaced
  group: kubesolv.io
  names:
    kind: CubeState
    plural: cubestates
    singular: cubestate
    shortNames:
    - cubestates
    - cubestate
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            oneOf:
            - required: [ "scramble" ]
            - required: [ "state" ]
            properties:
              scramble:
                type: string
              state:
                type: string
          status:
            type: object
