apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: solvers.kubesolv.io
spec:
  scope: Namespaced
  group: kubesolv.io
  names:
    kind: Solver
    plural: solvers
    singular: solver
    shortNames:
    - solvers
    - solver
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required: [ "image", "mode" ]
            properties:
              name:
                type: string
              image:
                type: string
              description:
                type: string
              mode:
                type: string
                enum:
                - standalone
                - mpi
                default: standalone
          status:
            type: object
